#include<bits/stdc++.h>
using namespace std ;
typedef long long ll ;

void solve(){

	int x,y ;
	cin>>x>>y ;

	if(y==0){
		cout<<"Airborne wins."<<"\n" ;
	}
	else
	{
		cout<<"Pagfloyd wins."<<"\n" ;
	}
	
}

int main(){

#ifndef ONLINE_JUDGE
	freopen("input.txt", "r", stdin) ;
	freopen("output.txt", "w", stdout) ;
#endif
	
	int y ;

	//y=1 ;
	cin>>y ;

	while(y--)
	{	
		solve() ;
	}

}